version: '3'
services:
  jupyter:
    image: decinho13/base-notebook:ros-tf
    ports:
      - "8888:8888"
    volumes:
      - jupyter_data:/home

  ros-kinetic:
    image: decinho13/ros-final:1.2.1
    ports:
      - "8080:8080"
      - "7000:7000"
      - "8181:8181"
    environment:
      DISPLAY=$DISPLAY
      NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - jupyter_data:/root

  vrep:
    image: decinho13/docker-vrep-novnc:1.3.0
    ports:
      - "9000:9000"
      - "5643:5643"
    environment:
      NVIDIA_VISIBLE_DEVICES=0
      DISPLAY=$DISPLAY
    volumes:
      -jupyter_data:/root

  blender:
    image: decinho13/blender-docker:1.0.0
    ports:
      - "8008:8008"
    volumes:
      - jupyter_data:/root

  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_host'] = 'postgresql'
        gitlab_rails['db_port'] = '5432'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'ci5ahLielieY'
        gitlab_rails['db_database'] = 'gitlab_prod'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'utf8'
        redis['enable'] = false
        gitlab_rails['redis_host'] = 'redis'
        gitlab_rails['redis_port'] = '6379'
    ports:
      - "2222:80"
    restart: always
    volumes:
      - data:/var/opt/gitlab

  redis:
    image: redis:4

  postgresql:
    image: postgres:9
    environment:
      - POSTGRES_USER=gitlab
      - POSTGRES_PASSWORD=ci5ahLielieY
      - POSTGRES_DB=gitlab_prod
    volumes:
      - pgdata:/var/lib/postgresql

  nginx:
    image: nginx
    ports:
      - "8009:80"
    volumes:
      html:/usr/share/nginx/html
      
volumes:
  data:
  pgdata:
  jupyter_data:
  html:
